// <auto-generated />
using System;
using AdminPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminPortal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdminPortalDbContext))]
    [Migration("20260818080948_AddAssessmentManagement")]
    partial class AddAssessmentManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminPortal.Domain.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GroupLv1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("group_lv1id");

                    b.Property<Guid>("GroupLv2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("group_lv2id");

                    b.Property<Guid>("GroupLv3Id")
                        .HasColumnType("uuid")
                        .HasColumnName("group_lv3id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<int?>("RowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("row_index");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_assessments");

                    b.HasIndex("GroupLv1Id")
                        .HasDatabaseName("ix_assessments_group_lv1id");

                    b.HasIndex("GroupLv2Id")
                        .HasDatabaseName("ix_assessments_group_lv2id");

                    b.HasIndex("GroupLv3Id")
                        .HasDatabaseName("ix_assessments_group_lv3id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_assessments_updated_by_user_id");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AssessmentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_assessment_groups");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_assessment_groups_updated_by_user_id");

                    b.ToTable("assessment_groups", (string)null);
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("HalfDayPart")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("half_day_part");

                    b.Property<bool?>("IsExcused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_excused");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("SheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("sheet_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("StudentCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_code_snapshot");

                    b.Property<string>("StudentFullNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name_snapshot");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("StudentNickNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nick_name_snapshot");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance_records");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_attendance_records_updated_by_user_id");

                    b.HasIndex("SheetId", "AttendanceDate")
                        .HasDatabaseName("ix_attendance_records_sheet_id_attendance_date");

                    b.HasIndex("SheetId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_records_sheet_id_student_id");

                    b.HasIndex("StudentId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_records_student_id_attendance_date");

                    b.ToTable("attendance_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_records_status_fields", "(status = 'Present' AND half_day_part IS NULL AND is_excused IS NULL AND duration_minutes IS NULL) OR (status = 'AbsentFullDay' AND half_day_part IS NULL AND is_excused IS NOT NULL AND duration_minutes IS NULL) OR (status = 'AbsentHalfDay' AND (half_day_part IS NULL OR half_day_part IN ('Morning', 'Afternoon')) AND is_excused IS NOT NULL AND duration_minutes IS NULL) OR (status = 'OneToOneHour' AND half_day_part IS NULL AND is_excused IS NULL AND duration_minutes = 60) OR (status = 'Unmarked' AND half_day_part IS NULL AND is_excused IS NULL AND duration_minutes IS NULL)");
                        });
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AttendanceSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("GroupCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("group_code_snapshot");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name_snapshot");

                    b.Property<string>("HistoricalRecoveryReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recovery_reason");

                    b.Property<Guid>("ResponsibleTeacherIdSnapshot")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_teacher_id");

                    b.Property<string>("ResponsibleTeacherNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsible_teacher_name_snapshot");

                    b.Property<string>("SnapshotSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("snapshot_source");

                    b.Property<int?>("SourceSnapshotVersion")
                        .HasColumnType("integer")
                        .HasColumnName("source_snapshot_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_attendance_sheets");

                    b.HasAlternateKey("Id", "AttendanceDate")
                        .HasName("ak_attendance_sheets_id_attendance_date");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_attendance_sheets_created_by_user_id");

                    b.HasIndex("ResponsibleTeacherIdSnapshot")
                        .HasDatabaseName("ix_attendance_sheets_responsible_teacher_id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_attendance_sheets_updated_by_user_id");

                    b.HasIndex("AttendanceDate", "GroupId")
                        .HasDatabaseName("ix_attendance_sheets_attendance_date_group_id");

                    b.HasIndex("GroupId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_sheets_group_id_attendance_date");

                    b.ToTable("attendance_sheets", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_sheets_source", "(snapshot_source = 'CurrentSnapshot' AND source_snapshot_version IS NOT NULL AND recovery_reason IS NULL) OR (snapshot_source = 'HistoricalRecovery' AND source_snapshot_version IS NULL AND recovery_reason IS NOT NULL AND recovery_reason = btrim(recovery_reason) AND recovery_reason <> '')");

                            t.HasCheckConstraint("ck_attendance_sheets_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<DateTimeOffset>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_sessions_refresh_token_hash");

                    b.HasIndex("UserId", "RevokedAt", "RefreshTokenExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_user_id_revoked_at_refresh_token_expires_at");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<DateTimeOffset?>("GroupAssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_assigned_at");

                    b.Property<Guid?>("GroupAssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_assigned_by");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guardian_name");

                    b.Property<string>("GuardianPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("guardian_phone");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nick_name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_code");

                    b.Property<string>("StudyMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("study_mode");

                    b.Property<short>("StudyWeekdayMask")
                        .HasColumnType("smallint")
                        .HasColumnName("study_weekday_mask");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("GroupAssignedByUserId")
                        .HasDatabaseName("ix_students_group_assigned_by_user_id");

                    b.HasIndex("StudentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_students_student_code")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("GroupId", "Status", "Id")
                        .HasDatabaseName("ix_students_group_id_status_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_students_status_created_at_id");

                    b.ToTable("students", null, t =>
                        {
                            t.HasCheckConstraint("ck_students_study_mode", "study_mode IN ('OneToOne', 'FullDay')");

                            t.HasCheckConstraint("ck_students_study_weekday_mask", "study_weekday_mask BETWEEN 1 AND 63");

                            t.HasCheckConstraint("ck_students_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.StudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ResponsibleTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_teacher_id");

                    b.Property<DateTimeOffset>("SnapshotChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_changed_at");

                    b.Property<int>("SnapshotVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("snapshot_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_student_groups");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_student_groups_code")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ResponsibleTeacherId")
                        .HasDatabaseName("ix_student_groups_responsible_teacher_id");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_student_groups_status_created_at_id");

                    b.ToTable("student_groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_student_groups_snapshot_version", "snapshot_version >= 1");
                        });
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AttendanceEditWindowDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)7)
                        .HasColumnName("attendance_edit_window_days");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("TeacherCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("teacher_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.HasIndex("TeacherCode")
                        .IsUnique()
                        .HasDatabaseName("ix_teachers_teacher_code");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_teachers_user_id");

                    b.ToTable("teachers", null, t =>
                        {
                            t.HasCheckConstraint("ck_teachers_attendance_edit_window_days", "attendance_edit_window_days BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_teachers_teacher_code", "teacher_code = upper(btrim(teacher_code)) AND teacher_code <> ''");

                            t.HasCheckConstraint("ck_teachers_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_users_status_created_at_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("AdminPortal.Domain.Entities.AssessmentGroup", "GroupLv1")
                        .WithMany("AssessmentsLv1")
                        .HasForeignKey("GroupLv1Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_assessment_groups_group_lv1id");

                    b.HasOne("AdminPortal.Domain.Entities.AssessmentGroup", "GroupLv2")
                        .WithMany("AssessmentsLv2")
                        .HasForeignKey("GroupLv2Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_assessment_groups_group_lv2id");

                    b.HasOne("AdminPortal.Domain.Entities.AssessmentGroup", "GroupLv3")
                        .WithMany("AssessmentsLv3")
                        .HasForeignKey("GroupLv3Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_assessment_groups_group_lv3id");

                    b.HasOne("AdminPortal.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_users_updated_by_user_id");

                    b.Navigation("GroupLv1");

                    b.Navigation("GroupLv2");

                    b.Navigation("GroupLv3");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AssessmentGroup", b =>
                {
                    b.HasOne("AdminPortal.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_groups_users_updated_by_user_id");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("AdminPortal.Domain.Entities.Student", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_records_students_student_id");

                    b.HasOne("AdminPortal.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_records_users_updated_by_user_id");

                    b.HasOne("AdminPortal.Domain.Entities.AttendanceSheet", "Sheet")
                        .WithMany("Records")
                        .HasForeignKey("SheetId", "AttendanceDate")
                        .HasPrincipalKey("Id", "AttendanceDate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_records_attendance_sheets_sheet_id_attendance_da");

                    b.Navigation("Sheet");

                    b.Navigation("Student");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AttendanceSheet", b =>
                {
                    b.HasOne("AdminPortal.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_sheets_users_created_by_user_id");

                    b.HasOne("AdminPortal.Domain.Entities.StudentGroup", "Group")
                        .WithMany("AttendanceSheets")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_sheets_student_groups_group_id");

                    b.HasOne("AdminPortal.Domain.Entities.Teacher", "ResponsibleTeacherSnapshot")
                        .WithMany()
                        .HasForeignKey("ResponsibleTeacherIdSnapshot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_sheets_teachers_responsible_teacher_id");

                    b.HasOne("AdminPortal.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_sheets_users_updated_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Group");

                    b.Navigation("ResponsibleTeacherSnapshot");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("AdminPortal.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AuthSession", b =>
                {
                    b.HasOne("AdminPortal.Domain.Entities.User", "User")
                        .WithMany("AuthSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.Student", b =>
                {
                    b.HasOne("AdminPortal.Domain.Entities.User", "GroupAssignedByUser")
                        .WithMany()
                        .HasForeignKey("GroupAssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_students_users_group_assigned_by_user_id");

                    b.HasOne("AdminPortal.Domain.Entities.StudentGroup", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_students_student_groups_group_id");

                    b.Navigation("Group");

                    b.Navigation("GroupAssignedByUser");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.StudentGroup", b =>
                {
                    b.HasOne("AdminPortal.Domain.Entities.Teacher", "ResponsibleTeacher")
                        .WithMany("ResponsibleGroups")
                        .HasForeignKey("ResponsibleTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_groups_teachers_responsible_teacher_id");

                    b.Navigation("ResponsibleTeacher");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("AdminPortal.Domain.Entities.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("AdminPortal.Domain.Entities.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AssessmentGroup", b =>
                {
                    b.Navigation("AssessmentsLv1");

                    b.Navigation("AssessmentsLv2");

                    b.Navigation("AssessmentsLv3");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.AttendanceSheet", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.Student", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.StudentGroup", b =>
                {
                    b.Navigation("AttendanceSheets");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("ResponsibleGroups");
                });

            modelBuilder.Entity("AdminPortal.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthSessions");

                    b.Navigation("TeacherProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
